### ISSUE TITLE
how to set jvm arguments in cloud functions

### ISSUE THREAD

**Issue by abhishek-digisprint** [googleapis/java-functions#299]
We have a requirement to add the JVM argument in the cloud functions. Can anyone help how to add?

Below argument needs to add:
Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8

**Comment by averikitsch** [comment]
Hi @abhishek-digisprint, I apologize for the delay, but you can pass in JVM arguments via and environment variable: `_JAVA_OPTIONS`. For example:
```
gcloud functions deploy my-function \
--entry-point functions.HelloWorld \
--runtime java11 \
--trigger-http \
--set-env-vars _JAVA_OPTIONS="-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8" \
--region us-central1
```

Please reopen if this doesn't work for you.
